---
title: "References"
format: html
editor: visual
---

## [References]{.smallcaps}

Baxter, C. J. (2011). Captain Thunderbolt & his lady: The true story of bushrangers Frederick Ward & Mary Ann Bugg. Allen & Unwin.

CAPT. THUNDERBOLT, ALIAS WARD, THE BUSHRANGER. (1866, March 29). Maitland Mercury and Hunter River General Advertiser. http://nla.gov.au/nla.news-article18712031

CAPTAIN THUNDERBOLT. (1867, February 9). http://nla.gov.au/nla.news-article18730111

CAPTURE OF WARD, THE BUSHRANGER, AND PURSUIT OF THUNDERBOLT. (1866, April 12). Brisbane Courier. http://nla.gov.au/nla.news-article1265580

Colonial Summary. (1866, April 7). Wagga Wagga Express and Murrumbidgee District Advertiser. http://nla.gov.au/nla.news-article105998167

Cutrara, S., PhD, Academic, for the O. of the V. P., & University, Y. (2019). Historical Image Analysis. https://pressbooks.library.yorku.ca/dhssinstructorsguide/chapter/historical-image-analysis/

DOINGS OF THE BUSHRANGERS. (1866, April 28). Queenslander. http://nla.gov.au/nla.news-article20307313

Drucker, J. (2021). The Digital Humanities Coursebook: An Introduction to Digital Methods for Research and Scholarship. Routledge. https://doi.org/10.4324/9781003106531

Lambert, A. (2011). The search for Captain Thunderbolt: An interview with David Donaldson. Studies in Australasian Cinema, 5(1), 81--87.

Maxwell-Stewart, H. (1990). The Bushranger's and the Convict System of Van Diemen's Land, 1803- 1846.

Messner, A. (2018, October 1). Andrew Cunningham's 1870 Captain Thunderbolt Photographs. Andrew Messner.https://andrewmessner.net/2018/10/01/andrew-cunninghams-1870-thunderbolt-photographs/

ONE HUNDRED POUNDS REWARD. (1865, December 27). New South Wales Government Gazette. http://nla.gov.au/nla.news-article225255090

Pillai, P. G. (1974). The World of Social Bandits. Social Scientist, 2(11), 71--75. https://doi.org/10.2307/3516958

Terria Map. (n.d.). Retrieved June 9, 2023, from https://nationalmap.gov.au/

THE DEATH OF THE BUSHRANGER WARD, ALIAS THUNDERBOLT. (1870, May 28). Sydney Morning Herald. http://nla.gov.au/nla.news-article28419906

The Real Captain Thunderbolt. (1951, December 15). http://nla.gov.au/nla.news-article140335028

THUNDERBOLT AGAIN. (1867, June 1). Armidale Express and New England General Advertiser. http://nla.gov.au/nla.news-article187931551

## [Image Collection References]{.smallcaps}

Aussie\~mobs. (1973). Australian Bushranger Thunderbolt's Grave at Uralla, N.S.W. - 1973 \[Photo\]. https://www.flickr.com/photos/hwmobs/50549533183/

Bill. (2016). Cockatoo Island -- Our Pangaea. https://www.ourpangaea.net/?p=7745

Captain Thunderbolt (1955). (n.d.). Retrieved June 5, 2023, from https://www.imdb.com/title/tt0045606/mediaviewer/rm2330317569/?ref\_=tt_ov_i

Constable Alexander Binning Walker, who killed the bushranger Thunderbolt, ca. May-June 1870 / photographer A. Cunningham, Armidale. (n.d.). Retrieved June 5, 2023, from https://collection.sl.nsw.gov.au/record/1Drm3v59

Cunningham, A. (n.d.-a). Cadaver of Frederick Ward, the bushranger Captain Thunderbolt, ca. May-June 1870 / photographer A. Cunningham, Armidale. Retrieved June 5, 2023, from https://collection.sl.nsw.gov.au/record/1Jkm40oY

Cunningham, A. (n.d.-b). V.6 no.109---Thunderbolt, 1870 \~ Thunderbolt dead, 1870. Andrew Cunningham. Retrieved June 5, 2023, from https://collection.sl.nsw.gov.au/digital/4DlpPqybAwaKj

Cunningham, A. (1870a). 'Capture of Thun¬der¬bolt.' https://andrewmessner.net/wp-content/uploads/2019/04/Reenactment-768x510.jpg

Cunningham, A. (1870b). The spot where Thunderbolt was captured, 187- / photographer A. Cunningham, Armidale. https://andrewmessner.net/wp-content/uploads/2019/04/Cunningham-1870-KC-SLNSW-768x450.jpg

David. (n.d.). Looking for Captain Thunderbolt (Cecil Holmes, 1953) -- Senses of Cinema. Retrieved June 7, 2023, from https://www.sensesofcinema.com/wp-content/uploads/2014/02/Captain-Thunderbolt2-750x400.jpg

Francis, E. (1951). Captain Thunderbolt \[film production?\], 8 May 1951 / photographs by Eric Francis. https://collection.sl.nsw.gov.au/record/n5lX6Ja9#viewer

Frederick Ward aka bushranger Captain Thunderbolt biography. (n.d.). Retrieved June 7, 2023, from http://thunderboltbushranger.com.au/frederick-ward-biography.html

Frederick Ward, alias Thunderbolt. (1870). https://andrewmessner.net/wp-content/uploads/2019/04/ISN-8-6-70-Ward.png

Highranger. (1962). Thunderbolt Rock \[Photo\]. https://www.flickr.com/photos/highranger/15866886025/

Mary Ann Buggs. (n.d.). Retrieved June 5, 2023, from https://www.rahs.org.au/mary-ann-bugg-1834-1905/

Messner, A. (1870). Death of Thun¬der¬bolt, the bush¬ranger',. https://andrewmessner.net/wp-content/uploads/2019/04/IANHR-768x620.jpg

Messner, A. (2018). 'Capture of "Thun¬der¬bolt." https://andrewmessner.net/2018/10/01/andrew-cunninghams-1870-thunderbolt-photographs/

Paul Leader - Paulie's Time Off Photography. (2017). Statue of Captain Thunderbolt, gentleman bushranger, Uralla NSW - see below \[Photo\]. https://www.flickr.com/photos/bypaulleader/45175384235/

Published Engraving that appeared in the Australian Town and Country Journal on 4th of June 1870. (n.d.). Retrieved June 6, 2023, from https://andrewmessner.net/wp-content/uploads/2019/04/atcj-4-6-70-p24-ward-illustration-768x458.jpg

State Library of NSW. (n.d.). Retrieved June 9, 2023, from https://www.sl.nsw.gov.au/

'The Scene of "Thun¬der¬bolt's Death",. (1870). https://andrewmessner.net/wp-content/uploads/2019/04/isn-6-7-70-1-1-768x577.jpg

Home---Trove. (n.d.). Retrieved June 9, 2023, from https://trove.nla.gov.au/

Were bushrangers villains or heroes? \| MHNSW. (n.d.). Retrieved June 6, 2023, from https://images.slm.com.au/fotoweb/embed/2022/12/56888b115d7a4d86b3b858dcea67d76e.jpg
